# Example configuration for zero-to-JupyterHub

hub:
  config:
    KubeSpawner:
      http_timeout: 60
  extraConfig:
    10-modify-pod: |
      def modify_pod_hook(spawner, pod):
          # First container is jhproxy/guacamole, move user volume to user container
          pod.spec.containers[1].volume_mounts = pod.spec.containers[0].volume_mounts
          pod.spec.containers[0].volume_mounts = None
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook

singleuser:
  image:
    name: ghcr.io/manics/jupyter-guacamole
    tag: main
  storage:
    # Uncomment to disable persistent storage
    # type: none
    homeMountPath: /home/ubuntu
  # Use default entrypoint
  cmd:
  cloudMetadata:
    blockWithIptables: false
  extraEnv:
    GUACD_HOST: localhost
    GUACD_PORT: "4822"
    PROTOCOL: vnc
    HOSTNAME: localhost
    # Optionally disable copy out and paste in
    # DISABLE_COPY: "true"
    # DISABLE_PASTE: "true"
  extraContainers:
    - name: ubuntu-mate
      image: ghcr.io/manics/ubuntu-mate-vnc:main
    - name: guacd
      image: docker.io/guacamole/guacd:1.5.0
  # startTimeout: 300
  # Use the default UID from the image
  uid:

prePuller:
  extraImages:
    guacd:
      name: docker.io/guacamole/guacd
      tag: 1.5.0
    ubuntu-mate-vnc:
      name: ghcr.io/manics/ubuntu-mate-vnc
      tag: main
